### PR TITLE
feat: add further AWS resources and data lookups

### PR DESCRIPTION
**Pull request by sjiveson**
Appreciate this project. 

Add new resources for AWS EC2 Transit Gateway, IAM, Route 53 Resolver and SES.

Unfortunately I can't run the pre-commit framework on this.

I did think maybe the route53resolver resources should go in a dedicated route53resolver directory rather than the route53 one. Let me know if that's what you think as well.

Lots more to come.

### CODE REVIEW

**Comment by JamesWoolfenden** [comment]
great stuff! ill take a look and get it merged! Mike have to fix the pr build it hasnt had masses of runs!

**Comment by sjiveson** [comment]
Ah, hadn't spotted those. Cool, I'll add them tomorrow morning. Cheers

**Comment by sjiveson** [comment]
Example resources added James. Cheers

**Comment by JamesWoolfenden** [comment]
thanks for your contributions!

**Pull request merged**
